### ISSUE TITLE
Weird behaviour mixing ranges and variables

### ISSUE THREAD

**Issue by Owumaro** [giovannicalo/brackets-coffeescript#2]
Hi,

When using CoffeeScript's ranges (for i in [1..10]) with variables, I get a weird coloring. Here is a code example :

```
data = [12, 151, 12151, 215121, 1215112]

for i in [1..data.length]
  console.log data[i]
```

And a screenshot :

![rangevarcolors](https://cloud.githubusercontent.com/assets/5205295/7474477/fdddb5bc-f341-11e4-9148-132a72dea05d.png)

The weirdest thing is that it depends on the letter : a-f get green, also o and x. The others turn purple.

**Comment by giovannicalo** [comment]
It depends on the letter because those in the range `[a-f]` are valid hexadecimal numbers, while `o` and `x` mark respectively octal and hexadecimal notations.

However, of course it's not intended, will fix it as soon as possible.

**Comment by giovannicalo** [comment]
Seems to be fixed, let me know if it still isn't in some special cases.
